[package]
name = "simple_voxels"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.6"
winit = { version = "0.29", features = ["android-native-activity"] }
env_logger = "0.10"
log = "0.4"
wgpu = "25.0"
pollster = "0.3"
cfg-if = "1.0.0"
